### ISSUE TITLE
Play next when episode is completely done 

### ISSUE THREAD

**Issue by razzeee** [im85288/service.nextup.notification#13]
If you set the addon to play the next episode as default. It seems like it will skip before the end of the episode at - 1 sec from the end instead of skipping when the episode is completely done.

**Comment by razzeee** [comment]
One way to fix it might be by using the same way to detect that the episode ended that the trakt addon uses. 
I'm currently sick, but I can return with details of you like.

**Comment by im85288** [comment]
Yes that would be great thanks. From memory I did it that way because once the episode had actually ended I did not have control to be able to start the next episode. If there is a better way then of course I'll try to implement that.

**Comment by razzeee** [comment]
I actually started to implement that, as it would also fix the trakt ratings not showing up, but it seems like I never uploaded it anywhere so it might be lost.

**Comment by razzeee** [comment]
I think I would try to capture the needed data as you do now, but trigger the playback of the next episode via a monitor object calling the onPlaybackEnded method, like here https://github.com/trakt/script.trakt/blob/master/service.py#L508

See http://mirrors.kodi.tv/docs/python-docs/15.x-isengard/xbmc.html#Monitor for the documentation.

**Comment by im85288** [comment]
Ok thanks, I'll try and play with this on the weekend.

**Comment by war59312** [comment]
See: https://github.com/trakt/script.trakt/issues/256

**Comment by HydrelioxGitHub** [comment]
Any solution found to this problem ?

**Comment by im85288** [comment]
No solution, I thought about this a bit more and even If I do handle the episode ending gracefully (when there is no user intervention) the problem for trakt will still remain when the user chooses to start watching the next episode before the end of the show. 

Is there a way for this addon to notify the trakt one that an episode playback has ended.

**Comment by razzeee** [comment]
Not right now, but we could craft that I guess.

**Comment by im85288** [comment]
Ok great, well I'm ready to integrate something along those lines when you are.

**Comment by razzeee** [comment]
We could use this? https://github.com/ruuk/script.module.addon.signals
So you need to send a signal and I need to subscript to it in trakt, if I understood right.

```
# In target addon
import AddonSignals
​
def callback(data):
    # Do something with data

AddonSignals.registerSlot(sender.addon.id, signal_name, callback)
​
​
#In source addon
import AddonSignals
​
AddonSignals.sendSignal(signal_name, {'some': 'data'})
```

**Comment by im85288** [comment]
Looks good

I added the following to the NextUp addon that get's called just prior to playing the next episode

`AddonSignals.sendSignal("NEXTUPWATCHEDSIGNAL", {'episodeid': self.currentepisodeid})
`

I think that is enough info for you or do you need anything else?

**Comment by razzeee** [comment]
Working flawless as far as I can tell. :)
See https://github.com/Razzeee/script.trakt/commit/3d77790f1d8405b337616a06741b897cc345de40

Thanks to @ruuk for the addon signals module

Btw I would still like to see a graceful approach for playing the next episode without interaction.

**Comment by im85288** [comment]
Great, I'll send a new version to the kodi repo with the changes included. Thanks again

**Comment by razzeee** [comment]
@im85288 
thank you, I don't want to harass you but gracefully waiting till the episode played the last second before skipping to the next one would still be appreciated. I know it's not an easy task.

**Comment by im85288** [comment]
I'll take a look into that tomorrow. It does involve quite a lot of code changes but I agree that would be a more elegant way of handling auto playback when there has been no user intervention.

**Comment by im85288** [comment]
I made an attempt at this today and it seems to be working correctly. However I cannot test the trakt scrobbling. I only now send the event above when the user has chosen to end playback before the end of the current episode. Can you give it a test when you get a chance? Thanks

**Comment by razzeee** [comment]
Works fine without interaction, I think that was what you wanted me to test?
I'm not sure if it skips gracefully, I have to check some more file for that.

**Comment by im85288** [comment]
Yeah thanks, I wasn't sure if the trakt scrobbling would still work without me sending the event when playback ended without interaction. Should work correctly now under all circumstances.

**Comment by razzeee** [comment]
When I let one episode end gracefully and skip to the ending of the next, it seems to throw this:

``````
22:33:20 T:11872   DEBUG: NEXTUP SERVICE NOTIFICATION Player -> logMsg : ONPLAYBACK_ENDED
22:33:20 T:11872   DEBUG: NEXTUP SERVICE NOTIFICATION Service -> logMsg : Netflix style autoplay succeeded.
22:33:20 T:11872   DEBUG: NEXTUP SERVICE NOTIFICATION Service -> logMsg : playtime is 632
22:33:20 T:11872   DEBUG: NEXTUP SERVICE NOTIFICATION Service -> logMsg : randomunwatchedtime is 600
22:33:20 T:11872   DEBUG: NEXTUP SERVICE NOTIFICATION Service -> logMsg : Exception in Playback Monitor Service: cannot concatenate 'str' and 'int' objects```
``````

**Comment by im85288** [comment]
Thanks I'll have a look into that. Is it only a problem in the log or did you notice any problems with trakt/next up.

**Comment by razzeee** [comment]
I don't get a nextup popup for the 2nd episode. So the error has to be there somewhere.

**Comment by im85288** [comment]
Ok thanks, I'll try and reproduce this weekend to see what's up.
