### ISSUE TITLE
Unwatched bug?

### ISSUE THREAD

**Issue by razzeee** [im85288/service.nextup.notification#17]
I think there is a new bug with unwatched?

When watching the last episode of a show (didn't test the other case) I get an popup with an random episode at about 10mins watching. Doesen't happen if I skip to minute ten, so it seems like it's counting somewhere.
And it seems like the lenght of the episode is doesn't change it happening at minute 10.

**Comment by im85288** [comment]
No that's correct that it shows a brief logo of an unwatched at 10 mins, it tries to pick one the same genre as the show your currently watching. Supposed to be like a little reminder of a related show your watching. It was off by default before, but is now on.

**Comment by razzeee** [comment]
Well then it's not showing correctly with kodi v17 and probably v16? I only get a black window with an episode title and number. So no way to know which show and no screenshot/artwork.

**Comment by im85288** [comment]
Strange, It works fine on my skin. I wined why the logos not displaying correctly for you.

**Comment by razzeee** [comment]
![image](https://cloud.githubusercontent.com/assets/5943908/14769259/b548cc98-0a55-11e6-8fc5-b3cc151f6d37.png)

**Comment by im85288** [comment]
Thanks for the screenshot, the background there is an error on my part. Not sure why you have no logo though, so I added a fallback to clear art. Can you re try with the latest 2 files I recently pushed?

**Comment by razzeee** [comment]
Not exactly better :/
![image](https://cloud.githubusercontent.com/assets/5943908/14769438/68ba6b5e-0a58-11e6-99b4-19829ed82c05.png)

**Comment by im85288** [comment]
Did you also grab UnwatchedInfo.py? Does your media not have logo/clear art available..I put a new version up with the text colour changed to white

**Comment by im85288** [comment]
I added a fallback to fanart image (in UnwatchedInfo.py)...hopefully that shows for you now. No idea how it will look though :)

**Comment by razzeee** [comment]
![image](https://cloud.githubusercontent.com/assets/5943908/14769502/0aa20976-0a5a-11e6-9bb4-fff71b246096.png)

**Comment by im85288** [comment]
Thanks, that looks better. I'll send a new version to the Kodi repo.

If your happy, I'll close the issue?

**Comment by razzeee** [comment]
Well I guess the issue is done, I will probably disable the setting. We should really get a skinner to redo those default dialogs.
Sorry. :(

**Comment by im85288** [comment]
Yes that would be great, even better if we could convince Kodi to integrate it into the core. Cheers

**Comment by im85288** [comment]
Btw it looks slightly better with logos

[img]http://i.imgur.com/B7O8R2k.jpg[/img]

**Comment by razzeee** [comment]
@im85288 core would take it with with a kiss, if you can code it in a sane way in c++ :)

ah, that's what it should look like :)
I would like something, that's more in line with the other dialogs (never seen the are you still watching dialog)

**Comment by im85288** [comment]
You lost me at c++ :) Java yes but not c++. 

Maybe once skinners notice the new dialog for unwatched, they may come up with new ideas. Something not too distracting was the aim for this one, kind of following some of the us tv shows that advertise upcoming shows.

**Comment by razzeee** [comment]
I'll try to get some of the core skinner to take a look at it. Let's see if someone takes it up.

I'm coming from C# so the jump to C++ was basically the same for me, as coming from Java. It's totally possible.
