### ISSUE TITLE
NextUP for liveTV

### ISSUE THREAD

**Issue by piotrasd** [im85288/service.nextup.notification#19]
Hi
Could you extended your addon for show in LiveTV what will next  - based on EPG even ? 
I think that is possible - it will great ! for LiveTV see this

For replace ClearART, you can use thumb from EPG event (some EPG provider or scraper delivery this)
and some skin using this showing info about program or channel icon or animated word "NEXT" and under this epg event with timer count

**Comment by im85288** [comment]
No that is not possible as the addon has no reference to live tv.
