### ISSUE TITLE
service.py has left several classes in memory that we couldn't clean up

### ISSUE THREAD

**Issue by nSpecter** [im85288/service.nextup.notification#25]
Anything I can do to address a kodi.log entry I've been seeing forever? --

NOTICE: NEXTUP SERVICE NOTIFICATION Service -> KODI Version: 17.3 Git:20170525-nogitfound
NEXTUP SERVICE NOTIFICATION Version: 1.0.35
...
NOTICE: NEXTUP SERVICE NOTIFICATION Service -> ======== STOP NEXTUP SERVICE NOTIFICATION ========
WARNING: CPythonInvoker(21, /home/nspectre/.kodi/addons/service.nextup.notification/service.py): the python script "/home/nspectre/.kodi/addons/service.nextup.notification/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon4xbmc6PlayerE

**Comment by im85288** [comment]
I'm not sure about this one, closing as it does not seem to effect anything but the logs.
