### ISSUE TITLE
[feature request] Adaptive end time notification

### ISSUE THREAD

**Issue by Lucki** [im85288/service.nextup.notification#26]
Suprised I haven't found something for this feature request, but nice to have:

Make the end time where the notification pops up adaptive, because different series have different offsets for the closing credits. To get a good notification the user has to change the end time seconds according to the watched series.
Example: one series has closing credits for about 40 seconds, the next series has closing credits for about 3 minutes. So with an end time of 40 seconds from the first series the user has to wait 2 minutes 20 seconds closing credits before he can skip the last 40 seconds.

Possibillities to archieve this:
- Maybe there's a database online where the closing credits offset is already stored which can be used or created from user input. Problem here can be different versions where the closing credits have different lenghts. Edit: [Found this post, seems promising.](https://forums.thetvdb.com/viewtopic.php?p=117538#p117538)
- Scan around the end for mostly black screen with some pixels white (If Kodi can scan the video). Problem here are fancy closing credits or a video after them. Also dark videos can be problematic.
- More?

Considering the amount of work this feature request will problably never get into this. Please tell me otherwise.

**Comment by im85288** [comment]
This would be an awesome addition but as you hinted at there does not seem to be anyway to do it currently. The link you provided looks promising and is something to keep an eye on. If you find any other info on how to achieve this please post it here and hopefully it can be achieved at some stage in the future.

**Comment by Lucki** [comment]
I've found [Stinger scene notification](https://forum.kodi.tv/showthread.php?tid=254004) which uses [ChapterDB](http://www.chapterdb.org) for getting the last chapter. They're often tagged as `End Credits` or `End Titles`, they're accurate but sadly only exist for movies.
There's also described that [TheMovieDB](https://www.themoviedb.org/) can has tags called as `aftercreditsstinger` and `duringcreditsstinger` which should represent the same if I haven't misread, but I couldn't find more to this. Since TheMovieDB also lists series there's a possiblity these tags also exist for episodes.
Maybe this can help you or lead to a relationship with the other plugin.

**Comment by Animizio** [comment]
Any news for this??? :)
