### ISSUE TITLE
Kodi Crash when Postplay Screen is deactivated

### ISSUE THREAD

**Issue by mikeb93** [im85288/service.nextup.notification#28]
Hi, my Kodi is Crashing when Nextup Postplay Screen is deactivated and the next video file should be played.

This is what the crashlog says:

> 15:20:45.580 T:140469513692928  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : playing media episode id 1104
> 15:20:45.763 T:140470410622656  NOTICE: CVideoPlayer::CloseFile()
> 15:20:45.764 T:140470410622656  NOTICE: VideoPlayer: waiting for threads to exit
> 15:20:45.764 T:140468747106048  NOTICE: CVideoPlayer::OnExit()
> 15:20:45.764 T:140468747106048  NOTICE: Closing stream player 1
> 15:20:45.764 T:140468747106048  NOTICE: Waiting for audio thread to exit
> 15:20:45.769 T:140468738713344   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
> 15:20:45.769 T:140468738713344  NOTICE: thread end: CVideoPlayerAudio::OnExit()
> 15:20:45.769 T:140468747106048  NOTICE: Closing audio device
> 15:20:45.809 T:140468747106048  NOTICE: Deleting audio codec
> 15:20:45.809 T:140468747106048  NOTICE: Closing stream player 2
> 15:20:45.809 T:140468747106048  NOTICE: waiting for video thread to exit
> 15:20:45.824 T:140468730320640  NOTICE: thread end: video_thread
> 15:20:45.824 T:140468747106048  NOTICE: deleting video codec
> 15:20:45.827 T:140470410622656  NOTICE: VideoPlayer: finished waiting
> 15:20:45.828 T:140470410622656  NOTICE: VideoPlayer: Opening: smb://192.168.0.201/TV/Malcolm In The Middle/Season 02/Malcolm in the Middle - 2x04 - Dinner Out.avi
> 15:20:45.828 T:140468747106048  NOTICE: Creating InputStream
> 15:20:45.886 T:140468747106048  NOTICE: Creating Demuxer
> 15:20:46.345 T:140470410622656   ERROR: Error trying to retrieve an item that's out of range

Full crashlog: https://pastebin.com/nRF5n5Vi
Seems like the plugin retreives a huge json list of episodes. Looks even like it gets all episodes of that show.

Everything works better with Postplay Screen enabled. But even then the new episode is playing in the background and starts over when the plugin is finished counting down.

Is there something I can do or is this a Bug?

**Comment by im85288** [comment]
Hello, this is something I have not managed to reproduce. For now I will set this as closed as it may have silently been resolved with the latest releases. If it still occurs in the new versions please create a new issue.

**Comment by mikeb93** [comment]
Hi, this issue is still happening on my setup.
I'm using libreelec's latest version right now (8.2.5 I think?) With Aeon Nox Theme.
Every time the notification appears (when it's still 30sec's until the next episode), Kodi crashes as soon as I hit the play butten of that notification.

How can I help with troubleshooting this for you?

**Comment by im85288** [comment]
Hi, I have stopped supporting this addon (it will not be available in versions of Leia and onwards soon) as I replaced it with [Up Next](https://github.com/im85288/service.upnext/wiki) which is available in the Kodi repo from leia onwards. There is no post play screen in the new version. It may be something I add in the future but at the moment I have no plans to do it. Cheers

**Comment by mikeb93** [comment]
Hi, thx I'll move over to Up Next.
Cheers
