### ISSUE TITLE
tvshowid not recognized with netflix strm files

### ISSUE THREAD

**Issue by hawkeyexp** [im85288/service.nextup.notification#30]
Hi,

last time some parts in the netflix addon from asciidisco has changed by me related to strm files and metadata. The strm files now provide a minimum information as m3u header which contains title season and episode. When Episodes was displayed in listing inside the addon some more metadata is cache and provided. But in both cases nextup service can't identify the tvshowid. While looking inside your source code i noticed you included some checks for strm files (checkStrms).
Can you possible extend these checks ?

Following results are possible with latest strm files generated by the netflix addon:

Minimum Metadata:

`07:47:30.364 T:228  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got active player {
                                            	"id": 1,
                                            	"jsonrpc": "2.0",
                                            	"result": [
                                            		{
                                            			"playerid": 1,
                                            			"type": "video"
                                            		}
                                            	]
                                            }
07:47:30.366 T:228  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Getting details of now  playing media
07:47:30.390 T:228  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got details of now playing media{
                                            	"id": 1,
                                            	"jsonrpc": "2.0",
                                            	"result": {
                                            		"item": {
                                            			"episode": -1,
                                            			"genre": [],
                                            			"label": "Arrow - S03E01",
                                            			"playcount": 0,
                                            			"season": -1,
                                            			"showtitle": "",
                                            			"tvshowid": -1,
                                            			"type": "unknown"
                                            		}
                                            	}
                                            }`

With cached metadata:

`07:58:32.072 T:228  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got active player {
                                            	"id": 1,
                                            	"jsonrpc": "2.0",
                                            	"result": [
                                            		{
                                            			"playerid": 1,
                                            			"type": "video"
                                            		}
                                            	]
                                            }
07:58:32.075 T:228  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Getting details of playing media
07:58:32.106 T:228  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got details of playing media{
                                            	"id": 1,
                                            	"jsonrpc": "2.0",
                                            	"result": {
                                            		"item": {
                                            			"episode": 1,
                                            			"label": "Die Rückkehr",
                                            			"playcount": 0,
                                            			"season": 1,
                                            			"showtitle": "Arrow",
                                            			"tvshowid": -1,
                                            			"type": "episode"
                                            		}
                                            	}
                                            }`

**Comment by im85288** [comment]
Hi, I’m not sure what changes I need to make as it was another contributor that added the checkStrms method. Are you saying I now get back from the Netflix addon what is shown above in the cached metadata section?

**Comment by hawkeyexp** [comment]
The two sets of data are only caused by 2 ways inside the addon - i have only posted both to make sure you know all possible situations :-)
I will have a look inside the commits what exactly was changed by the contributors commit. I have a funxction written fur the netflix addon which delivers the showid by title and possible it can replace the strm-function. If it is working i give you a pull request and you can check it out.

**Comment by hawkeyexp** [comment]
Hi as announced i have done a rework :-)
I skipped the old method and replaced it with a universal one. If tvshowid is missing (-1) a lookup into the kodi database is done and tvshowid is set. Same is done for episodeid. In my case it now works perfect with playing files based on strm files with missing tvshowid if title season and episode is set to player.
I did not change any other behaviour of the addon.
Have a look and try it out for bugs please. https://github.com/hawkeyexp/service.nextup.notification/commits/strmfix

**Comment by im85288** [comment]
Great thanks, I will check it out today

**Comment by im85288** [comment]
Could you submit a PR please

**Comment by hawkeyexp** [comment]
One question cause it makes my crazy - where exactly is the image defined shown in nextup notification window (usually the fanart image)? First i noticed the fanart image which is set in nextup xml but it is not the correct one.

**Comment by im85288** [comment]
The images for the nextup window are set in here: https://github.com/im85288/service.nextup.notification/blob/master/resources/lib/NextUpInfo.py and the ones for the postplay window are set in the postplayinfo.py file. So if images are missing from Netflix it’s possible they are not correctly set in the Netflix addon. I’ll close this issue but feel free to reply on it.

**Comment by hawkeyexp** [comment]
I know this is set there but have a look on this:

i have added some dialogues to make it visible.

`    def onInit(self):
        self.action_exitkeys_id = [10, 13]

        image = self.item['art'].get('tvshow.poster', '')
        thumb = self.item['art'].get('thumb', '')
        clearartimage = self.item['art'].get('tvshow.clearart', '')
        landscapeimage = self.item['art'].get('tvshow.landscape', '')
        fanartimage = self.item['art'].get('tvshow.fanart', '')
        overview = self.item['plot']
        tvshowtitle = self.item['showtitle']
        name = self.item['title']
        playcount = self.item['playcount']

        dlg = xbmcgui.Dialog()
        dlg.ok("Image / Thumb",str(image),str(thumb))
        dlg.ok("Clear / Land",str(clearartimage),str(landscapeimage))
        dlg.ok("Fanart",str(fanartimage))`

As you can see the image url's are present in both types in content but the fanart image is only shown when content is a normal video (1st set of images) - I have no idea why - possible you ?

Working with normal videos from kodi db:
![screenshot000](https://user-images.githubusercontent.com/761728/31310806-d9df711a-ab9e-11e7-9026-4f58a26d982d.png)
![screenshot001](https://user-images.githubusercontent.com/761728/31310807-d9e28706-ab9e-11e7-9864-8b5be789c45f.png)
![screenshot002](https://user-images.githubusercontent.com/761728/31310810-d9ea9e64-ab9e-11e7-9438-b0a7aff53b6c.png)

Not working with strm from kodi db:
![screenshot003](https://user-images.githubusercontent.com/761728/31310808-d9e72c3e-ab9e-11e7-8984-0de6bac1463e.png)
![screenshot004](https://user-images.githubusercontent.com/761728/31310811-d9ee60f8-ab9e-11e7-8a8c-95cc115e7b7e.png)
![screenshot005](https://user-images.githubusercontent.com/761728/31310809-d9e90d4c-ab9e-11e7-9c6e-72d8080a85d1.png)

**Comment by im85288** [comment]
I had a look at the netflix addon to see what it sets for the images and this is the code:

`art = {'fanart': self.default_fanart}
        #Cleanup art
        art.update({
            'landscape': '',
            'thumb': '',
            'fanart': '',
            'poster': ''
        })

        if 'boxarts' in dict(entry).keys():
            art.update({
                'poster': entry['boxarts']['big'],
                'landscape': entry['boxarts']['big'],
                'thumb': entry['boxarts']['small'],
                'fanart': entry['boxarts']['big']
            })
            # Download image for exported listing
            if 'title' in entry:
                self.library.download_image_file(title=entry['title'].encode('utf-8'), url=str(entry['boxarts']['big']))

        if 'interesting_moment' in dict(entry).keys():
            art.update({
                'poster': entry['interesting_moment'],
                'fanart': entry['interesting_moment']
            })
        if 'thumb' in dict(entry).keys():
            art.update({'thumb': entry['thumb']})
        if 'fanart' in dict(entry).keys():
            **art.update({'fanart': entry['fanart']})**
        if 'poster' in dict(entry).keys():
            art.update({'poster': entry['poster']})
        li.setArt(art)`

As you can see it is not adding **tvshow.fanart** so it fails to be found in this addon (or any other that uses tvshow.fanart) but tvshow.poster seems to work for the image variable when that has only been added as poster above so I could be wrong. Worthwhile adding it in the netflix addon to see if it works.

**Comment by im85288** [comment]
Actually scrap everything above! I misread your comment...hmm now that is very strange indeed. No logical explanation for that one...can you open the url it gives for the second fanart in a browser window...or is it the same as the first one.

**Comment by hawkeyexp** [comment]
You are right - no logical explanation :-) I love cryzy sh... like this :-)
I will test the url's ...

**Comment by hawkeyexp** [comment]
Ok i found something - seems the url directs to a missing file on thetvdb.com :-(

By the way: how do you think to change from fanart to thumbnail of episode like the postplaysceen does and using same method with setting image to show as property ? It will make it more clear and thumb  makes more sense to me as preview of next episode.Additinal we can check of the url is ok and file exists and alternate show the fanart image. Ifg you agree i will try to mod it and send you a pull.

**Comment by hawkeyexp** [comment]
I really don't know how the dialog get's the image. No change i tried in the code results in a changed image - possible thumb instead of fanart etc. - can you please check your code and point me a working solution to change to viewed image ?

**Comment by im85288** [comment]
Hi, do you mean the the url's pointing at the wrong images? I guess that must be coming from the netflix addon. I'm more than happy for you to add features you think can improve the addon, At the moment I am toying with a hybrid pop up and post play screen.

**Comment by hawkeyexp** [comment]
Seems it was a buggy url from scraper. But i have played arround for example commented out the fanart image in your xml but a image was still shown etc. or replaced with a custom infi label but no change - crazy stuff i can't understand at the moment

**Comment by hawkeyexp** [comment]
I'm back online - but this week only prtitial cause i had to move to new apartment - i have notuived your posta about the minimal header and detect episode and season from there - i had added this not long ago as m3u header - old exports didn't had this - will work on it next time.

**Comment by Animizio** [comment]
Hey,
Any news about this?
Just tried to use the last Version from the official Repo and its Not working with Streams for me. 
I get season/episodeid - 1
