### ISSUE TITLE
Can't exit

### ISSUE THREAD

**Issue by andres-asm** [im85288/service.nextup.notification#36]
This is happening on PC (windows, linux) but not on android
I can't exit by pressing on the home button or backspace.

I'm kodi 17 in all cases.

**Comment by im85288** [comment]
Sorry I will need more details than that, can you provide a screenshot of where you are referring to.

Thanks

**Comment by McButton** [comment]
This is an issue. I'm using Linux / Krypton. 
The main screen that gives episode options sticks. The countdown works, the selection of alternate shows works, the fanart change button works. The HOME button does nothing. Hitting home on the remote also does nothing. You basically have to let the video play and hit stop to get back to the Kodi menu.

**Comment by McButton** [comment]
Also, on the same screen, the episode shown in the very bottom left corner description text drags across the whole screen. The 2nd episode stays within it's box.

**Comment by McButton** [comment]
The above issue seems to be working with the Yatse remote app for Android. The issue seems somehow linked to the keymapping  of remote/keypad perhaps.
