### ISSUE TITLE
[Request/Question] Start scraping before post-play?

### ISSUE THREAD

**Issue by drinfernoo** [im85288/service.nextup.notification#47]
I'm not sure how the code is set up now, but it seems like it could start scraping for links (for content added to the library from a streaming add-on) as soon as the preview pops up... That way the post-play screen could potentially go directly into the next episode, without having to scrape AFTER the time out. I don't know Python, but if you could point me to where in the code this might like, I could fiddle with it and try to make a PR if it helps.

Is this possible?

**Comment by im85288** [comment]
I'm not following this, could you try and explain again what it is you are trying to achieve?

**Comment by drinfernoo** [comment]
Basically, the actual scraping for an episode doesn't seem to start until *after* the post-play timeout is over. Basically, starting the scraping whenever the preview pops up would simply make the transition from one episode to the next be more seamless, since it's more likely to have found a viable source by then.

**Comment by Animizio** [comment]
+1 would also like this (if I finally get this Addon to work..)
