### ISSUE TITLE
No audio on auto next video

### ISSUE THREAD

**Issue by McButton** [im85288/service.nextup.notification#49]
This seems new. This was fine a few weeks ago. Now, it appears that after allowing the video to load the after screen, the video that plays has no audio.

I can't recall changing anything to my system.
Chromebox. Krypton. Madnox Skin.

**Comment by McButton** [comment]
Tested this further. It seems to be working again.
It may have something to do with the connection of the source. If the connection isn't fully stable, it may lose the audio stream.
Might not be anything the add-on needs to fix, but something to be aware of.

**Comment by im85288** [comment]
Thanks let's close this for now and open a new one if there is a confirmed issue with the addon
