### ISSUE TITLE
not even working at all

### ISSUE THREAD

**Issue by cabban** [im85288/service.nextup.notification#50]
could be great never came a pop up from my library

**Comment by im85288** [comment]
I need a lot more information than that to be able to try and help you. Can you describe in detail what is happening and post your kodi log with the settings of the addon (found in services->next up notification) set to DEBUG. Please assure NOT to set the global kodi log level to debug only the addon settings.

**Comment by cabban** [comment]
@im85288 thank. actually nothing have a season in my library from an addon, then have next up , but nothing happening :)

**Comment by cabban** [comment]
the debug is on then next ;)`?

**Comment by im85288** [comment]
Check out this link: http://kodi.wiki/view/Log_file/Easy for how to post a log....but remember NOT to turn on debug in the general kodi settings...only in the addon settings

**Comment by cabban** [comment]
it says error when log :( so this is not easy to get a  han on:P

**Comment by im85288** [comment]
Ok if you know the location of your kodi log just paste it into pastebin and post the link here, you need to restart Kodi first though so the log is clean and then play an episode that you expect to have an episode next to play (bear in mind this addon does not fully support strm files)

**Comment by cabban** [comment]
okej, which files then ? :) is it only downloaded files ?

**Comment by im85288** [comment]
Have a read about kodi log files and where to locate them for your device, google is your friend here. I have to get back to work

**Comment by cabban** [comment]
15:46:40.005 T:8476  NOTICE: special://profile/ is mapped to: special://masterprofile/
15:46:40.005 T:8476  NOTICE: -----------------------------------------------------------------------
15:46:40.005 T:8476  NOTICE: Starting Kodi (17.6 Git:20171114-a9a7a20). Platform: Windows NT x86 32-bit
15:46:40.005 T:8476  NOTICE: Using Release Kodi x32 build
15:46:40.005 T:8476  NOTICE: Kodi compiled Dec 10 2017 by MSVC 190024215 for Windows NT x86 32-bit version 10.0 (0x0A000000)
15:46:40.006 T:8476  NOTICE: Running on Sony Corporation SVL2413L1EB with Windows 10, kernel: Windows NT x86 64-bit version 10.0
15:46:40.006 T:8476  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
15:46:40.006 T:8476  NOTICE: Host CPU: Unknown, 4 cores available
15:46:40.006 T:8476  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
15:46:40.006 T:8476  NOTICE: Running with restricted rights
15:46:40.008 T:8476  NOTICE: Aero is enabled
15:46:40.008 T:8476  NOTICE: special://xbmc/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p
15:46:40.008 T:8476  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p
15:46:40.008 T:8476  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p/addons
15:46:40.008 T:8476  NOTICE: special://masterprofile/ is mapped to: C:\Users\cabba\AppData\Roaming\Kodi\userdata
15:46:40.008 T:8476  NOTICE: special://home/ is mapped to: C:\Users\cabba\AppData\Roaming\Kodi\
15:46:40.008 T:8476  NOTICE: special://temp/ is mapped to: C:\Users\cabba\AppData\Roaming\Kodi\cache
15:46:40.008 T:8476  NOTICE: special://logpath/ is mapped to: C:\Users\cabba\AppData\Roaming\Kodi\
15:46:40.008 T:8476  NOTICE: The executable running is: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\Kodi.exe
15:46:40.013 T:8476  NOTICE: Local hostname: DESKTOP-5HT4S00
15:46:40.013 T:8476  NOTICE: Log File is located: C:\Users\cabba\AppData\Roaming\Kodi\/kodi.log
15:46:40.013 T:8476  NOTICE: -----------------------------------------------------------------------
15:46:40.020 T:8476  NOTICE: load settings...
15:46:40.031 T:8476 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
15:46:40.031 T:8476 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
15:46:40.036 T:8476  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
15:46:40.037 T:8476  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
15:46:40.037 T:8476  NOTICE: Default Video Player: VideoPlayer
15:46:40.037 T:8476  NOTICE: Default Audio Player: paplayer
15:46:40.037 T:8476  NOTICE: Disabled debug logging due to GUI setting. Level 0.
15:46:40.037 T:8476  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
15:46:40.037 T:8476  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
15:46:40.038 T:8476  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
15:46:40.038 T:8476  NOTICE: Loaded playercorefactory configuration
15:46:40.038 T:8476  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
15:46:40.038 T:8476  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
15:46:40.052 T:8476  NOTICE: Running database version Addons27
15:46:40.121 T:8476  NOTICE: ADDONS: Using repository repository.xbmc.org
15:46:40.121 T:8476  NOTICE: ADDONS: Using repository repository.blamo
15:46:40.121 T:8476  NOTICE: ADDONS: Using repository repository.tmb
15:46:40.121 T:8476  NOTICE: ADDONS: Using repository repository.xbmchub
15:46:40.121 T:8476  NOTICE: ADDONS: Using repository repository.BludhavenGrayson
15:46:40.154 T:2148  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: stream type "STREAM_TYPE_DTSHD" on device "SONY TV-14 (2- NVIDIA High Definition Audio)" seems to be not supported.
15:46:40.154 T:2148  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: stream type "STREAM_TYPE_TRUEHD" on device "SONY TV-14 (2- NVIDIA High Definition Audio)" seems to be not supported.
15:46:40.155 T:2148  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: stream type "STREAM_TYPE_EAC3" on device "SONY TV-14 (2- NVIDIA High Definition Audio)" seems to be not supported.
15:46:40.157 T:2148  NOTICE: CAESinkWASAPI::EnumerateDevicesEx: sample rate 192khz on device "SONY TV-14 (2- NVIDIA High Definition Audio)" seems to be not supported.
15:46:40.165 T:2148  NOTICE: Found 2 Lists of Devices
15:46:40.165 T:2148  NOTICE: Enumerated DIRECTSOUND devices:
15:46:40.165 T:2148  NOTICE:     Device 1
15:46:40.165 T:2148  NOTICE:         m_deviceName      : {6AF70016-E808-4DFF-A444-F88718FABF19}
15:46:40.165 T:2148  NOTICE:         m_displayName     : HDMI - SONY TV-14 (2- NVIDIA High Definition Audio)
15:46:40.165 T:2148  NOTICE:         m_displayNameExtra: DIRECTSOUND: SONY TV-14 (2- NVIDIA High Definition Audio)
15:46:40.165 T:2148  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
15:46:40.165 T:2148  NOTICE:         m_channels        : FL,FR
15:46:40.165 T:2148  NOTICE:         m_sampleRates     : 48000
15:46:40.165 T:2148  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_RAW
15:46:40.165 T:2148  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
15:46:40.165 T:2148  NOTICE:     Device 2
15:46:40.165 T:2148  NOTICE:         m_deviceName      : {DCEEEDC3-DC23-4D69-AB6D-7E75FF66A693}
15:46:40.165 T:2148  NOTICE:         m_displayName     : Speakers - Högtalare/Hörlurar (Realtek High Definition Audio)
15:46:40.165 T:2148  NOTICE:         m_displayNameExtra: DIRECTSOUND: Högtalare/Hörlurar (Realtek High Definition Audio)
15:46:40.165 T:2148  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:46:40.165 T:2148  NOTICE:         m_channels        : FL,FR
15:46:40.165 T:2148  NOTICE:         m_sampleRates     : 48000
15:46:40.165 T:2148  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
15:46:40.165 T:2148  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
15:46:40.165 T:2148  NOTICE:     Device 3
15:46:40.165 T:2148  NOTICE:         m_deviceName      : default
15:46:40.166 T:2148  NOTICE:         m_displayName     : default
15:46:40.166 T:2148  NOTICE:         m_displayNameExtra:
15:46:40.166 T:2148  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:46:40.166 T:2148  NOTICE:         m_channels        : FL,FR
15:46:40.166 T:2148  NOTICE:         m_sampleRates     : 48000
15:46:40.166 T:2148  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
15:46:40.166 T:2148  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
15:46:40.166 T:2148  NOTICE: Enumerated WASAPI devices:
15:46:40.166 T:2148  NOTICE:     Device 1
15:46:40.166 T:2148  NOTICE:         m_deviceName      : {6AF70016-E808-4DFF-A444-F88718FABF19}
15:46:40.166 T:2148  NOTICE:         m_displayName     : HDMI - SONY TV-14 (2- NVIDIA High Definition Audio)
15:46:40.166 T:2148  NOTICE:         m_displayNameExtra: WASAPI: SONY TV-14 (2- NVIDIA High Definition Audio)
15:46:40.166 T:2148  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
15:46:40.166 T:2148  NOTICE:         m_channels        : FL,FR
15:46:40.166 T:2148  NOTICE:         m_sampleRates     : 192000,48000,44100
15:46:40.166 T:2148  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_RAW
15:46:40.166 T:2148  NOTICE:         m_streamTypes     : STREAM_TYPE_DTSHD,STREAM_TYPE_TRUEHD,STREAM_TYPE_EAC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512,STREAM_TYPE_AC3
15:46:40.166 T:2148  NOTICE:     Device 2
15:46:40.166 T:2148  NOTICE:         m_deviceName      : {DCEEEDC3-DC23-4D69-AB6D-7E75FF66A693}
15:46:40.166 T:2148  NOTICE:         m_displayName     : Speakers - Högtalare/Hörlurar (Realtek High Definition Audio)
15:46:40.166 T:2148  NOTICE:         m_displayNameExtra: WASAPI: Högtalare/Hörlurar (Realtek High Definition Audio)
15:46:40.166 T:2148  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:46:40.166 T:2148  NOTICE:         m_channels        : FL,FR
15:46:40.166 T:2148  NOTICE:         m_sampleRates     : 192000,176400,96000,88200,48000,44100
15:46:40.166 T:2148  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_RAW
15:46:40.166 T:2148  NOTICE:         m_streamTypes     : STREAM_TYPE_DTSHD,STREAM_TYPE_TRUEHD,STREAM_TYPE_EAC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512,STREAM_TYPE_AC3
15:46:40.166 T:2148  NOTICE:     Device 3
15:46:40.166 T:2148  NOTICE:         m_deviceName      : default
15:46:40.166 T:2148  NOTICE:         m_displayName     : default
15:46:40.166 T:2148  NOTICE:         m_displayNameExtra:
15:46:40.166 T:2148  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:46:40.166 T:2148  NOTICE:         m_channels        : FL,FR
15:46:40.166 T:2148  NOTICE:         m_sampleRates     : 192000,176400,96000,88200,48000,44100
15:46:40.166 T:2148  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_RAW
15:46:40.166 T:2148  NOTICE:         m_streamTypes     : STREAM_TYPE_DTSHD,STREAM_TYPE_TRUEHD,STREAM_TYPE_EAC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512,STREAM_TYPE_AC3
15:46:40.207 T:8476  NOTICE: Found screen: Generic PnP Monitor on NVIDIA GeForce GT 620M, adapter 0.
15:46:40.207 T:8476  NOTICE: Primary mode: 1920x1080@ 60.00 - Full Screen
15:46:40.208 T:8476  NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
15:46:40.209 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.209 T:8476  NOTICE: Additional mode: 640x480@ 59.94 - Full Screen
15:46:40.209 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.209 T:8476  NOTICE: Additional mode: 664x440@ 60.00 - Full Screen
15:46:40.209 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.209 T:8476  NOTICE: Additional mode: 664x440@ 59.94 - Full Screen
15:46:40.210 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.210 T:8476  NOTICE: Additional mode: 664x528@ 60.00 - Full Screen
15:46:40.210 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.210 T:8476  NOTICE: Additional mode: 664x528@ 59.94 - Full Screen
15:46:40.211 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.211 T:8476  NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
15:46:40.211 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.211 T:8476  NOTICE: Additional mode: 800x600@ 59.94 - Full Screen
15:46:40.211 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.211 T:8476  NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
15:46:40.212 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.212 T:8476  NOTICE: Additional mode: 1024x768@ 59.94 - Full Screen
15:46:40.212 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.212 T:8476  NOTICE: Additional mode: 1176x664@ 60.00 - Full Screen
15:46:40.212 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.212 T:8476  NOTICE: Additional mode: 1176x664@ 59.94 - Full Screen
15:46:40.213 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.213 T:8476  NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
15:46:40.213 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.213 T:8476  NOTICE: Additional mode: 1280x720@ 59.94 - Full Screen
15:46:40.213 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.213 T:8476  NOTICE: Additional mode: 1280x768@ 60.00 - Full Screen
15:46:40.214 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.214 T:8476  NOTICE: Additional mode: 1280x768@ 59.94 - Full Screen
15:46:40.214 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.214 T:8476  NOTICE: Additional mode: 1280x1024@ 60.00 - Full Screen
15:46:40.215 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.215 T:8476  NOTICE: Additional mode: 1280x1024@ 59.94 - Full Screen
15:46:40.215 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.215 T:8476  NOTICE: Additional mode: 1360x768@ 60.00 - Full Screen
15:46:40.216 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.216 T:8476  NOTICE: Additional mode: 1360x768@ 59.94 - Full Screen
15:46:40.216 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.216 T:8476  NOTICE: Additional mode: 1366x768@ 60.00 - Full Screen
15:46:40.217 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.217 T:8476  NOTICE: Additional mode: 1366x768@ 59.94 - Full Screen
15:46:40.217 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.217 T:8476  NOTICE: Additional mode: 1400x1050@ 60.00 - Full Screen
15:46:40.217 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.217 T:8476  NOTICE: Additional mode: 1400x1050@ 59.94 - Full Screen
15:46:40.218 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.218 T:8476  NOTICE: Additional mode: 1440x900@ 60.00 - Full Screen
15:46:40.218 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.218 T:8476  NOTICE: Additional mode: 1440x900@ 59.94 - Full Screen
15:46:40.218 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.218 T:8476  NOTICE: Additional mode: 1680x1050@ 60.00 - Full Screen
15:46:40.219 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.219 T:8476  NOTICE: Additional mode: 1680x1050@ 59.94 - Full Screen
15:46:40.219 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.219 T:8476  NOTICE: Additional mode: 1768x992@ 60.00 - Full Screen
15:46:40.219 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.219 T:8476  NOTICE: Additional mode: 1768x992@ 59.94 - Full Screen
15:46:40.220 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.220 T:8476  NOTICE: Additional mode: 1920x1080@ 60.00 - Full Screen
15:46:40.220 T:8476  NOTICE: Additional mode: 1920x1080@ 59.94 - Full Screen
15:46:40.220 T:8476  NOTICE: Additional mode: 720x480@ 60.00 - Full Screen
15:46:40.220 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.220 T:8476  NOTICE: Additional mode: 720x480@ 59.94 - Full Screen
15:46:40.221 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.221 T:8476  NOTICE: Additional mode: 720x576@ 60.00 - Full Screen
15:46:40.221 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.221 T:8476  NOTICE: Additional mode: 720x576@ 59.94 - Full Screen
15:46:40.221 T:8476  NOTICE: Previous line repeats 2 times.
15:46:40.221 T:8476  NOTICE: Additional mode: 1920x1080@ 30.00i - Full Screen
15:46:40.222 T:8476  NOTICE: Checking resolution 15
15:46:40.596 T:9076  NOTICE: Running database version Addons27
15:46:40.599 T:9076  NOTICE: Running database version ViewModes6
15:46:40.601 T:9076  NOTICE: Running database version Textures13
15:46:40.606 T:9076  NOTICE: Running database version MyMusic60
15:46:40.610 T:9076  NOTICE: Running database version MyVideos107
15:46:40.613 T:9076  NOTICE: Running database version TV29
15:46:40.616 T:9076  NOTICE: Running database version Epg11
15:46:40.801 T:8476 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
15:46:40.967 T:8476  NOTICE: initialize done
15:46:40.967 T:8476  NOTICE: Running the application...
15:46:40.968 T:8476  NOTICE: starting upnp client
15:46:40.972 T:5636  NOTICE: ES: Starting UDP Event server on port 9777
15:46:40.972 T:5636  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
15:46:44.011 T:7604  NOTICE: next-episode.net: service started
15:46:44.281 T:8092  NOTICE: [COLOR red][ PLACENTA DEBUG ] : [/COLOR]: ######################### PLACENTA ############################
15:46:44.281 T:8092  NOTICE: [COLOR red][ PLACENTA DEBUG ] : [/COLOR]: ####### CURRENT PLACENTA VERSIONS REPORT ######################
15:46:44.281 T:8092  NOTICE: [COLOR red][ PLACENTA DEBUG ] : [/COLOR]: ### PLACENTA PLUGIN VERSION: 1.0.4 ###
15:46:44.281 T:8092  NOTICE: [COLOR red][ PLACENTA DEBUG ] : [/COLOR]: ### PLACENTA SCRIPT VERSION: 1.0.7 ###
15:46:44.281 T:8092  NOTICE: [COLOR red][ PLACENTA DEBUG ] : [/COLOR]: ### TEAM REBIRTH REPOSITORY VERSION: 0.0.3 ###
15:46:44.281 T:8092  NOTICE: [COLOR red][ PLACENTA DEBUG ] : [/COLOR]: ###############################################################
15:46:44.359 T:1716  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.6), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
15:46:45.156 T:1064  NOTICE: Indigo NOTICE: STARTING Indigo SERVICE
15:46:45.163 T:6804   ERROR: XFILE::CDirectory::GetDirectory - Error getting
15:46:45.236 T:9212   ERROR: Previous line repeats 6 times.
15:46:45.236 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> logMsg : Starting NextUp Service
15:46:45.275 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> logMsg : ========  START NEXTUP SERVICE NOTIFICATION  ========
15:46:45.281 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> logMsg : KODI Version: 17.6 Git:20171114-a9a7a20
15:46:45.329 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> logMsg : NEXTUP SERVICE NOTIFICATION Version: 1.0.37
15:46:45.334 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Starting playback monitor service
15:46:46.671 T:6572  NOTICE: URLResolver: Initializing URLResolver version: 4.0.16
15:47:20.855 T:8960  NOTICE: Previous line repeats 1 times.
15:47:20.855 T:8960  NOTICE: metahandler: Initializing MetaHandlers version: 3.0.2
15:47:21.193 T:8960  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.10.2
15:47:21.700 T:8960   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
15:47:21.728 T:8960  NOTICE: metahandler: No SQLite rows requiring update
15:47:22.922 T:8476  NOTICE: VideoPlayer: Opening: https://bjdobr16.s.llnwi.net/v1/user3253/b178dbf7748fdfd5e177d23fe04f8164/SUB.4.720p.mp4
15:47:22.922 T:8476 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:47:22.967 T:8476   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
15:47:22.967 T:8476   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
15:47:22.968 T:2824  NOTICE: Creating InputStream
15:47:23.291 T:2824  NOTICE: Creating Demuxer
15:47:23.526 T:2824  NOTICE: Opening stream: 0 source: 256
15:47:23.526 T:2824  NOTICE: Creating video codec with codec id: 28
15:47:23.527 T:2824  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
15:47:23.527 T:2824  NOTICE: Creating video thread
15:47:23.527 T:2824  NOTICE: Opening stream: 1 source: 256
15:47:23.527 T:2824  NOTICE: Finding audio codec for: 86018
15:47:23.527 T:5788  NOTICE: running thread: video_thread
15:47:23.528 T:2824  NOTICE: Creating audio thread
15:47:23.528 T:908  NOTICE: running thread: CVideoPlayerAudio::Process()
15:47:23.528 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:23.538 T:908  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
15:47:23.573 T:8476  NOTICE: D3D: rendering method forced to DXVA processor
15:47:23.573 T:8476  NOTICE: DXVA::CProcessorHD::InitProcessor: Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:no.
15:47:23.574 T:8476 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
15:47:23.769 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got active player {"id":1,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
15:47:23.771 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Getting details of now  playing media
15:47:23.790 T:9212  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got details of now playing media{"id":1,"jsonrpc":"2.0","result":{"item":{"episode":-1,"genre":[],"label":"Baby Daddy S06E04","playcount":0,"season":-1,"showtitle":"","tvshowid":-1,"type":"unknown"}}}
15:47:23.831 T:5788  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 40000
15:47:24.056 T:8960   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
15:47:24.057 T:8960  NOTICE: metahandler: No SQLite rows requiring update
15:47:38.099 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:38.111 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:47:39.980 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:40.001 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:47:42.247 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:42.284 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:47:44.598 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:44.639 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:47:50.930 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:50.960 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:47:52.382 T:8960   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
15:47:52.384 T:8960  NOTICE: metahandler: No SQLite rows requiring update
15:47:55.199 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:55.238 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:47:57.648 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:57.696 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:47:59.894 T:5788  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:47:59.912 T:5788  NOTICE: DXVA::CDecoder::Close - closing decoder
15:48:04.680 T:8476  NOTICE: CVideoPlayer::CloseFile()
15:48:04.680 T:8476  NOTICE: VideoPlayer: waiting for threads to exit
15:48:04.687 T:2824  NOTICE: CVideoPlayer::OnExit()
15:48:04.687 T:2824  NOTICE: Closing stream player 1
15:48:04.687 T:2824  NOTICE: Waiting for audio thread to exit
15:48:04.710 T:908  NOTICE: thread end: CVideoPlayerAudio::OnExit()
15:48:04.710 T:2824  NOTICE: Closing audio device
15:48:04.726 T:2824  NOTICE: Deleting audio codec
15:48:04.726 T:2824  NOTICE: Closing stream player 2
15:48:04.726 T:2824  NOTICE: waiting for video thread to exit
15:48:04.750 T:5788  NOTICE: thread end: video_thread
15:48:04.750 T:2824  NOTICE: deleting video codec
15:48:04.751 T:2824  NOTICE: DXVA::CDecoder::Close - closing decoder
15:48:04.751 T:2824  NOTICE: DXVA::Close - closing decoder context
15:48:04.765 T:8476  NOTICE: VideoPlayer: finished waiting
15:48:04.931 T:8476  NOTICE: CVideoPlayer::CloseFile()
15:48:04.931 T:8476  NOTICE: VideoPlayer: waiting for threads to exit
15:48:04.931 T:8476  NOTICE: VideoPlayer: finished waiting
15:48:04.932 T:8476  NOTICE: CVideoPlayer::CloseFile()
15:48:04.932 T:8476  NOTICE: VideoPlayer: waiting for threads to exit
15:48:04.932 T:8476  NOTICE: VideoPlayer: finished waiting
15:48:06.526 T:3896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('tvshowid',)
                                            Traceback (most recent call last):
                                              File "C:\Users\cabba\AppData\Roaming\Kodi\addons\script.lazytv\service.py", line 357, in onPlayBackStopped
                                                pre_showid  = Main.nextprompt_info['tvshowid']
                                            KeyError: ('tvshowid',)
                                            -->End of Python script error report<--

**Comment by im85288** [comment]
The addon only supports content added to your local kodi database and not using other means such as Indigo etc.

I'll close this now but create a new one if you start to use kodi with your own content added to the kodi database.

**Comment by cabban** [comment]
@im85288 öh, how do u mean now, indigo kodi database? how to do thatm, thats illegal? or have a missing something, to download and seed

**Comment by im85288** [comment]
The problem with not having local content is shown up with this statement:

Got details of now playing media{"id":1,"jsonrpc":"2.0","result":{"item":{"episode":-1,"genre":[],"label":"Baby Daddy S06E04","playcount":0,"season":-1,"showtitle":"","tvshowid":-1,"type":"unknown"}}}

Everything is -1 meaning no local content.
