### ISSUE TITLE
[Kodi 18] Episode list remains every time next episode starts

### ISSUE THREAD

**Issue by beeeeswax** [im85288/service.nextup.notification#53]
This addon is working in Leia however each time Nextup begins playback of a new episode, it's not dismissing/hiding the episode list from the TV Series you're viewing.  I'm running the 64-bit nightly dated 30th March.

Here's a kodi log with the addon's own debug logging enabled: [https://pastebin.com/jnjYcm3q](url)

I believe the area of interest on the log is around timestamp 13:12:47

**Comment by im85288** [comment]
Closed as this addon has been replaced with up next
