### ISSUE TITLE
Question: dev

### ISSUE THREAD

**Issue by hawkeyexp** [im85288/service.nextup.notification#55]
Have you any plans to continue work on dev-branch ? I will do some work on my skipdb and would be know if you are interested to keep it in your code (cause it would be the better way to safe resources) or releasing a standalone-solution.

**Comment by im85288** [comment]
Hi, I’ve been too busy with personal work recently...but I aim to complete the EmbyCon integration at some stage. I’m happy to keep your changes in if we can get it to a stage where it’s water tight, unfortunately I will not have much time for support in the near future but yes please go ahead and submit PRs when your ready. Cheers

**Comment by hawkeyexp** [comment]
I'm still using it many times and my custom db is growing (if i have motivation to fill the entries *lol*)
The interesting question is which branch should i use as base - on dev you started a refactoring but never finished it - your emby branch seems to be latest working on and is based on master. So master as base ? I will keep it as seperated as possible for easy handling.

**Comment by im85288** [comment]
Very good question! It’s been so long I forgot where I was up to but as you said it was the Emby branch that was the one I was working on most recently. If you base it off the Emby branch I think that’s the best approach as the refactoring brought in a few bugs which I haven’t got the energy to resolve :) This weekend I will take a closer look and possibly create another branch for the skipdb changes if that’s easier to manage..but it would be based on the Emby one as I was very close to finishing that one.

**Comment by hawkeyexp** [comment]
ok

**Comment by im85288** [comment]
An interesting read if you haven’t seen it: https://forum.kodi.tv/showthread.php?tid=328614

In my head I still think getting an integration with Netflix (which knows the exact intro times) would be the most accurate first step. We could maybe also use the credits time to trigger the next up window
